### ISSUE TITLE
Question on creating 6 plots in a 3 rows by 2 columns configuration

### ISSUE THREAD

**Issue by hlalibe** [pplcc/plotext#2]
Hi,

I saw this post on Stack and its answer:
https://stackoverflow.com/questions/47557438/multiple-line-plots-sharing-abscissas-axis-in-gonum-plot

I see that it's possible to use loops to create 6 plots in a 3 rows by 2 columns configuration. But as i'm new to Go, the code given on the Stack link above is a little tricky for me to grasp completely.

I was trying to adapt your align example to produce a 3 x 2 configuration but bumping into errors. My last code is per following:

```
	table := plotext.Table{
		RowHeights: []float64{2, 2, 2}, //
		ColWidths:  []float64{1,1},
	}

	// see align_test.go for another example on how to construct this structure using loops
	plots := [][]*plot.Plot{[[]*plot.Plot{p1}, []*plot.Plot{p2}, []*plot.Plot{p3}], [[]*plot.Plot{p4}, []*plot.Plot{p5}, []*plot.Plot{p6}]}

	img := vgimg.New(450, 300)
	dc := draw.New(img)

	canvases := table.Align(plots, dc)
	plots[0][0].Draw(canvases[0][0])
	plots[1][0].Draw(canvases[1][0])
	plots[2][0].Draw(canvases[2][0])
	plots[0][1].Draw(canvases[0][1])
	plots[1][1].Draw(canvases[1][1])
	plots[2][1].Draw(canvases[2][1])
```
But that gives me this error message for the plots := line
 syntax error: unexpected comma, expecting ]

I've inserted extra [ ] to group plot 1,2,3 together and also 4,5,6
Is there a way to define the plots := line for a 3 rows by 2 columns without using loop ?

**Comment by pplcc** [comment]
Hi,

have a look at 

 plotext/table_test.go

Greetings!

Peter

**Comment by hlalibe** [comment]
ok thanks, it's a little more involving than what i thought
