### ISSUE TITLE
Data format for custplotter.NewCandlesticks( )

### ISSUE THREAD

**Issue by hlalibe** [pplcc/plotext#3]
Hi,

What is the data format that is expected by bars, err := custplotter.NewCandlesticks(data) ?

My data is formatted like this:
[[2 16435 16458 16435 16446 1] [3 16446 16458 16435.04 16455 1] .....]

I believe you are expecting something like this ?:
[{2 16435 16458 16435 16446 1} {3 16446 16458 16435.04 16455 1} .....]

I get this error with my data:
cannot use data (type [][]string) as type custplotter.TOHLCVer in argument to custplotter.NewCandlesticks:
	[][]string does not implement custplotter.TOHLCVer (missing Len method)

I'm new to go and i don't know how to create my data with this shape,

thanks for your help

**Comment by pplcc** [comment]
Hi,

are you reading the data from text files?

If you have some strings then you have to parse them into float64 values and put them into something implementing the TOHLCVer interface. You can use TOHLCVs. Have a look at

plotext/custplotter/tohlcv.go

You can find an example how to create TOHLCVs in

plotext/examples/tohlcvexampledata.go
```

data := make(custplotter.TOHLCVs, n)
loc, _ := time.LoadLocation("America/New_York")
for i := range data {
data[i].T = float64(time.Date(2000, 01, 02, 03, 04, 05, 0, loc).Add(time.Duration(i) * time.Minute).Unix())
data[i].O = fract[4*i]
data[i].H = math.Max(math.Max(fract[4*i], fract[4*i+1]), math.Max(fract[4*i+2], fract[4*i+3]))
data[i].L = math.Min(math.Min(fract[4*i], fract[4*i+1]), math.Min(fract[4*i+2], fract[4*i+3]))
data[i].C = fract[4*i+3]
data[i].V = (data[i].H - data[i].L + math.Abs(data[i].C-data[i].O)) * 100 // just use this as a fake volume
}
```

This example creates some fake data. Put your time into data[i].T and your parsed float64 values into data[i].O ... data[i].V.

Greetings!

Peter

**Comment by hlalibe** [comment]
Ok thanks Peter, I've implemented the TOHLCVer interface, it works now, i'm reading data from excel.
