### ISSUE TITLE
Can we set the bar width for Candlesticks chart ?

### ISSUE THREAD

**Issue by hlalibe** [pplcc/plotext#4]
Hi,

I'm using your code below to draw a candlestick chart, works nicely. 
Question: can we set the width of each bar ? I would need to make them wider:

```
p1, err := plot.New()
if err != nil {
	log.Panic(err)
}
p1.HideAxes()

bars, err := custplotter.NewCandlesticks(OHLCVmin)
if err != nil {
	log.Panic(err)
}
p1.Add(bars)
```

**Comment by pplcc** [comment]
Hi, 

two alternatives:

1. Alter custplotter.DefaultCandleWidthFactor (default is 3) at the beginning of you code before calling custplotter.NewCandlesticks. E. g.:

```
custplotter.DefaultCandleWidthFactor = 5;
bars, err := custplotter.NewCandlesticks(OHLCVmin)
```

2. Alter the CandleWidth member of bars after it was created by custplotter.NewCandlesticks. 

```
import (
	"gonum.org/v1/plot"
	"gonum.org/v1/plot/plotter"
	"gonum.org/v1/plot/vg"
	"gonum.org/v1/plot/vg/draw"
)

```
...

```
bars, err := custplotter.NewCandlesticks(OHLCVmin)
if err != nil {
	log.Panic(err)
}
bars.CandleWidth = vg.Length(5) * plotter.DefaultLineStyle.Width
p1.Add(bars)
```

I didn't test these suggestions... Hope one of them works for you!

Greetings!

Peter

**Comment by hlalibe** [comment]
Excellent !
If I don't come back on this thread it means it's working,

thanks Peter !
